encoder_config:
  target: vfmtok.core.layers.Encoder
  params:
    layer_type: normal
    image_size: 256
    patch_size: 16
    dim: 512
    in_channels: 1024
    depth: 6
    num_head: 8
    mlp_dim: 2048
    dim_head: 64
    dropout: 0.1
    n_carrier: 256
    enc_n_points: 4
    encoder_variant: deformable
    visual_encoder_config:
      target: vfmtok.modules.encoders.pretrained_enc_arch_siglip.SigLIPEmbedder
      is_trainable: False
      params:
        model_name: vit_large_patch16_siglip_384.v2_webli
        pretrained: True
        img_size: 384
        patch_size: 16
        feature_levels: [23]
        ckpt_path: ./weights/vit_large_patch16_siglip_384.v2_webli/model.safetensors
decoder_config:
  target: vfmtok.core.layers.Decoder
  params:
    layer_type: normal
    image_size: ${encoder_config.params.image_size}
    patch_size: ${encoder_config.params.patch_size}
    dim: ${encoder_config.params.dim}
    depth: ${encoder_config.params.depth}
    num_head: ${encoder_config.params.num_head}
    mlp_dim: ${encoder_config.params.mlp_dim}
    dim_head: ${encoder_config.params.dim_head}
    dropout: ${encoder_config.params.dropout}
    n_carrier: ${encoder_config.params.n_carrier}
